name: autotab

description: A music transcription app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  record: ^6.0.0
  provider: ^6.0.0
  permission_handler: ^12.0.0
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
